import PrelineScript from '@/app/_components/preline_script'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/assets/background.jpg')] bg-no-repeat bg-cover bg-center bg-blend-color-dodge`}
			>
				{children}
				<PrelineScript />
				<ToastContainer />
			</body>
			<PrelineScript />
		</html>
	)
}
